language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
install:
    - apt install gpg
    - pip install -r requirements/test.txt
script:
  - pytest
  - python -m flake8 pillar
  - coverage run --source pillar setup.py test


after_success:
  - codecov