language: python
arch:
  - amd64
  - arm64
os: linux
python:
  - "3.8"
  - "3.9"
  - "3.9-dev"
install:
    - pip install -r requirements/test.txt
script:
  - python -m unittest
  - python -m flake8 pillar
  - coverage run --source=pillar setup.py test


after_success:
  - codecov
