language: python
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
install:
    - pip install -r requirements/test.txt
script:
  - python -m unittest
  - python -m flake8 pillar
  - coverage run --source pillar setup.py test


after_success:
  - codecov
